version: '3'
services:
 elastic_search:
  image: docker.elastic.co/elasticsearch/elasticsearch:8.1.1
  container_name: es01
  environment:
   - discovery.type=single-node
   - node.name=es01
   - bootstrap.memory_lock=true
   - ES_JAVA_OPTS=-Xms1g -Xmx1g
   - ELASTIC_PASSWORD=testpass
  ports:
   - 9200:9200
   - 9300:9300
  networks:
   - elastic_network
 
#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.1.1
#    container_name: kbn01
#    environment:
#      SERVER_NAME: 'kibana.example.org'
#      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
#    ports:
#     - 5601:5601
#    depends_on:
#      - elastic_search
#    networks:
#     - elastic_network

networks:
  elastic_network:
    name: elastic_docker_example_net
