//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.09 at 11:58:46 AM IST 
//


package com.skill.profile.api.jaxb.types;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for skillProfileResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="skillProfileResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="skillProfiles" type="{http://skill-tracker.com/skill-profile-api-models}SkillProfileType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://skill-tracker.com/skill-profile-api-common}response"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "skillProfileResponse", namespace = "http://skill-tracker.com/skill-profile-api", propOrder = {
    "skillProfiles",
    "response"
})
@XmlRootElement(name = "SkillProfileResponse", namespace = "http://skill-tracker.com/skill-profile-api")
public class SkillProfileResponse {

    protected List<SkillProfileType> skillProfiles;
    @XmlElement(namespace = "http://skill-tracker.com/skill-profile-api-common", required = true)
    protected Response response;

    /**
     * Gets the value of the skillProfiles property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the skillProfiles property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSkillProfiles().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SkillProfileType }
     * 
     * 
     */
    public List<SkillProfileType> getSkillProfiles() {
        if (skillProfiles == null) {
            skillProfiles = new ArrayList<SkillProfileType>();
        }
        return this.skillProfiles;
    }

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link Response }
     *     
     */
    public Response getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response }
     *     
     */
    public void setResponse(Response value) {
        this.response = value;
    }

}
