//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.09 at 11:58:46 AM IST 
//


package com.skill.profile.api.jaxb.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for skillProfileRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="skillProfileRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="skillProfile" type="{http://skill-tracker.com/skill-profile-api-models}SkillProfileType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "skillProfileRequest", namespace = "http://skill-tracker.com/skill-profile-api", propOrder = {
    "skillProfile"
})
@XmlRootElement(name = "SkillProfileRequest", namespace = "http://skill-tracker.com/skill-profile-api")
public class SkillProfileRequest {

    protected SkillProfileType skillProfile;

    /**
     * Gets the value of the skillProfile property.
     * 
     * @return
     *     possible object is
     *     {@link SkillProfileType }
     *     
     */
    public SkillProfileType getSkillProfile() {
        return skillProfile;
    }

    /**
     * Sets the value of the skillProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkillProfileType }
     *     
     */
    public void setSkillProfile(SkillProfileType value) {
        this.skillProfile = value;
    }

}
